# Generated by Django 6.0.2 on 2026-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Asosiy karta, Naqd pul', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisoblar',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Transport, Oziq-ovqat, Maosh', max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Kirim'), ('EXPENSE', 'Chiqim')], default='EXPENSE', max_length=10)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Kirim'), ('EXPENSE', 'Chiqim')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(help_text='Operatsiya qilingan sana va vaqt')),
                ('comment', models.TextField(blank=True, help_text='Izoh qoldirish uchun', null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'db_table': 'transactions',
                'ordering': ['-date'],
            },
        ),
    ]
