# Generated by Django 6.0.2 on 2026-04-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
